### PR TITLE
adjust namespace

### PR DESCRIPTION
**Pull request by reinfi**
namespace change

### CODE REVIEW

**Review by lisachenko — APPROVED** [review]
Well done, approved PR. Who will be merging PR for this repo?

**Comment by reinfi** [comment]
I merged this as you have approved it. Generally I would say both of us all. Easy PRs could be one person, or he should mention the others if one thought the others should have a look.

Should we respect semantiv versioning at this point and already make it to version 2.0 ?

**Comment by lisachenko** [comment]
Sounds good, agreed.

**Comment by icanhazstring** [comment]
> Should we respect semantiv versioning at this point and already make it to version 2.0 ?

fine with me.

> Easy PRs could be one person, or he should mention the others if one thought the others should have a look.

good point there. As we all know what we are doing (hopefully :D) we can simply confirm with a single person. If things are unclear or a second opinion might come in handy we can simply mention the others

**Pull request merged**
